# Generated by Django 3.2.8 on 2022-03-11 21:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import manager.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Posts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blogCategory', models.CharField(max_length=30)),
                ('blogTitle', models.CharField(max_length=50)),
                ('postedOn', models.DateTimeField()),
                ('blogImage', models.ImageField(blank=True, null=True, upload_to=manager.models.upload_to2)),
                ('blogText', models.TextField(max_length=3000)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='author', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Details',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(max_length=30)),
                ('lastName', models.CharField(max_length=30)),
                ('gender', models.CharField(max_length=30)),
                ('bio', models.CharField(max_length=100)),
                ('profileImg', models.ImageField(blank=True, null=True, upload_to=manager.models.upload_to)),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dee', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
